nelmio_api_doc:
    documentation:
        info:
            title: My Payment API
            description: API для обработки финансовых транзакций
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
