<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260307002900 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Updated schema with outbox UUID, nullable payment_id and unique idempotency key';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP SEQUENCE idempotency_keys_id_seq CASCADE');
        $this->addSql('CREATE TABLE account (id VARCHAR(255) NOT NULL, balance VARCHAR(255) NOT NULL, currency VARCHAR(3) NOT NULL, version INT NOT NULL, PRIMARY KEY (id))');

        // ИСПРАВЛЕНИЕ 1: payment_id теперь DEFAULT NULL (без NOT NULL)
        $this->addSql('CREATE TABLE idempotency_key (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_id UUID NOT NULL, key VARCHAR(255) NOT NULL, request_hash VARCHAR(255) NOT NULL, payment_id UUID DEFAULT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY (id))');

        // ИСПРАВЛЕНИЕ 2: Добавили уникальный индекс, чтобы база не пускала дубликаты
        $this->addSql('CREATE UNIQUE INDEX idx_unique_key ON idempotency_key (key)');

        // ИСПРАВЛЕНИЕ 3: id теперь UUID, а payload - TEXT
        $this->addSql('CREATE TABLE outbox_message (id UUID NOT NULL, event_class VARCHAR(255) NOT NULL, payload TEXT NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, from_account_id UUID NOT NULL, to_account_id UUID NOT NULL, amount VARCHAR(25) NOT NULL, status VARCHAR(25) NOT NULL, PRIMARY KEY (id))');

        // Удаляем старые таблицы
        $this->addSql('ALTER TABLE idempotency_keys DROP CONSTRAINT idempotency_keys_account_id_fkey');
        $this->addSql('ALTER TABLE idempotency_keys DROP CONSTRAINT idempotency_keys_payment_id_fkey');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT payments_from_account_id_fkey');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT payments_to_account_id_fkey');
        $this->addSql('DROP TABLE accounts');
        $this->addSql('DROP TABLE idempotency_keys');
        $this->addSql('DROP TABLE payments');

        // Audit log
        $this->addSql('DROP INDEX idx_audit_event_created');
        $this->addSql('DROP INDEX idx_audit_entity_created');
        $this->addSql('ALTER TABLE audit_log ALTER id TYPE INT');
        $this->addSql('ALTER TABLE audit_log ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE audit_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE audit_log ALTER event_type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE audit_log ALTER entity_type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE audit_log ALTER entity_id TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE audit_log ALTER payload TYPE JSON');
        $this->addSql('ALTER TABLE audit_log ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE audit_log ALTER created_at DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // down() оставляем без изменений, он просто откатывает всё назад
        $this->addSql('CREATE SEQUENCE idempotency_keys_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE accounts (id UUID NOT NULL, balance NUMERIC(18, 2) NOT NULL, currency CHAR(3) NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT \'now()\' NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT \'now()\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE idempotency_keys (id BIGINT DEFAULT nextval(\'idempotency_keys_id_seq\'::regclass) NOT NULL, account_id UUID NOT NULL, key VARCHAR(64) NOT NULL, request_hash CHAR(64) NOT NULL, payment_id UUID DEFAULT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT \'now()\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_idem_payment ON idempotency_keys (payment_id)');
        $this->addSql('CREATE INDEX idx_idem_created ON idempotency_keys (created_at)');
        $this->addSql('CREATE UNIQUE INDEX idempotency_keys_account_id_key_key ON idempotency_keys (account_id, key)');
        $this->addSql('CREATE INDEX IDX_F3C9CAF99B6B5FBA ON idempotency_keys (account_id)');
        $this->addSql('CREATE TABLE payments (id UUID NOT NULL, from_account_id UUID NOT NULL, to_account_id UUID NOT NULL, amount NUMERIC(18, 2) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT \'now()\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_payments_status ON payments (status)');
        $this->addSql('CREATE INDEX idx_payments_to_created ON payments (to_account_id, created_at)');
        $this->addSql('CREATE INDEX idx_payments_from_created ON payments (from_account_id, created_at)');
        $this->addSql('CREATE INDEX IDX_65D29B32B0CF99BD ON payments (from_account_id)');
        $this->addSql('CREATE INDEX IDX_65D29B32BC58BDC7 ON payments (to_account_id)');
        $this->addSql('ALTER TABLE idempotency_keys ADD CONSTRAINT idempotency_keys_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE idempotency_keys ADD CONSTRAINT idempotency_keys_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT payments_from_account_id_fkey FOREIGN KEY (from_account_id) REFERENCES accounts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT payments_to_account_id_fkey FOREIGN KEY (to_account_id) REFERENCES accounts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE idempotency_key');
        $this->addSql('DROP TABLE outbox_message');
        $this->addSql('DROP TABLE payment');
        $this->addSql('ALTER TABLE audit_log ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE audit_log ALTER id SET DEFAULT nextval(\'audit_log_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE audit_log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE audit_log ALTER event_type TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE audit_log ALTER entity_type TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE audit_log ALTER entity_id TYPE UUID');
        $this->addSql('ALTER TABLE audit_log ALTER payload TYPE JSONB');
        $this->addSql('ALTER TABLE audit_log ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE audit_log ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('CREATE INDEX idx_audit_event_created ON audit_log (event_type, created_at)');
        $this->addSql('CREATE INDEX idx_audit_entity_created ON audit_log (entity_type, entity_id, created_at)');
    }
}
